---
title: "Untitled"
format: html
---

```{r}
library(tidyverse)
library(readr)
library(TMDb)

# Load TMDB data
key <- "c87bcab7333598a66552a72264adeb06"
id <- 550


# Tests:

# getting detailed info minus variables with multiple values
tmdb_test2 <- movie(api_key = key, id = 550)

tmdb_scalars <- tmdb_test2[sapply(tmdb_test2, function(x) length(x) == 1)]

tmdb_test_df2 <- as_tibble(tmdb_scalars)


# manually extract variables with multiple values
genres_df <- as_tibble(tmdb_test2$genres)
companies_df <- as_tibble(tmdb_test2$production_companies)
countries_df <- as_tibble(tmdb_test2$production_countries)


# get general info by page
top_rated <- movie_top_rated(api_key = key, page = 2)

top_rated_df <- as_tibble(top_rated)


# Creating top 2000 dataset:

top_rated_ids <- map_dfr(1:500, function(p) {
  page <- movie_top_rated(api_key = key, page = p)
  as_tibble(page$results) %>% select(id)
})

# function to get scalar fields for one movie safely
get_movie_scalars <- function(id, api_key) {
  tryCatch({
    m <- movie(api_key = api_key, id = id)
    scalars <- m[sapply(m, function(x) length(x) == 1)]
    as_tibble(scalars)
  }, error = function(e) {
    message(paste("Failed for ID:", id))
    return(NULL) # skip if not found
  })
}

movies_df_10k <- map_df(top_rated_ids$id, ~ get_movie_scalars(.x, key))

# Making correction from USD to JPY
movies_df <- movies_df %>% mutate(budget = if_else(title == "Paprika", 2600000, budget))
```

```{r warning = FALSE}
# Exploring the data


movies_df_working <- movies_df %>% filter(budget > 10000, revenue > 10000) %>% # set arbitrary budget and revenue lower bounds to filter out weird anomalies
  mutate(release_date = ymd(release_date),
         release_date_num = as.numeric(release_date),
         rev_budget_ratio = revenue / budget,
         title_short = str_trunc(title, width = 20, side = "right")) %>% # make revenue/budget variable
  arrange(desc(rev_budget_ratio)) %>%
  group_by(imdb_id) %>% # remove dupicate rows
  filter(n() == 1) %>%
  ungroup()
  
cults <- movies_df_working %>%
  filter(rev_budget_ratio < 2, vote_average > 7.8, original_language == "en") %>%
  mutate(before_2015 = if_else(release_date < "2015-01-01", "Pre-2015", "Post-2015"))

# preliminary thresholds for english language cult movies (for now this just means good movies that flopped)

library(ggrepel)

ggplot(cults, aes(x = rev_budget_ratio, y = vote_average, label = title_short, color = before_2015)) +
  geom_point() +
  geom_text_repel(size = 3) +
  labs(title = "Cult Classics", x = "Profitability (Revenue / Budget)", y = "Average Rating", color = "Release Date") +
  scale_color_manual(values = c("Pre-2015" = "deepskyblue", "Post-2015" = "orangered3")) +
  theme_classic()

cults_no_new_stuff <- movies_df_working %>%
  filter(rev_budget_ratio < 2, vote_average > 7.6, original_language == "en", release_date < "2010-01-01")

ggplot(cults_no_new_stuff, aes(x = rev_budget_ratio, y = vote_average, label = title_short)) +
  geom_point() +
  geom_text_repel(size = 3) +
  labs(title = "Cult Classics", x = "Profitability (Revenue / Budget)", y = "Average Rating") +
  theme_classic()
```

```{r}
Sys.setenv(OPENAI_API_KEY = "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")

library(ellmer)
library(dplyr)
library(tibble)
library(patchwork)

llm_input_10k <- movies_df_10k %>% filter(release_date < "2010-01-01", budget > 10, revenue > 10) %>% select(title, release_date) %>% mutate(prompt_text = paste0(
    "Title: ", title, ". Release date: ", release_date, "."))

# Run single-shot detection using formatted prompts (claim + evidence)
single_shot_results <- parallel_json_completion(
  system_prompt = "Evaluate whether or not each film is widely/definitively considered to be a 'cult classic'.",

  user_prompts = llm_input_10k$prompt_text,

  type_obj = type_object(
    llm_cult = type_string("Either 1 (a cult classic) or 0 (not a cult classic)")
  ),

  model = "gpt-4.1-mini"
)

# Add results to the df
movies_10k_w_llm <- movies_df_10k %>% filter(release_date < "2010-01-01", budget > 10, revenue > 10)

movies_10k_w_llm$llm_class_5 <- single_shot_results$llm_cult

table(movies_10k_w_llm$llm_class_2)



movies_10k_w_llm <- movies_10k_w_llm %>% mutate(llm_sum = as.numeric(llm_class_1) + as.numeric(llm_class_2) + as.numeric(llm_class_3) + as.numeric(llm_class_4) + as.numeric(llm_class_5),
                                                llm_class_final = if_else(llm_sum >= 4, 1, 0))

table(movies_10k_w_llm$llm_sum)

write.csv(movies_10k_w_llm, "data/raw/10k_pre-2010-01-01-w-llm-classification.csv")

movies_w_llm_classification <- movies_w_llm_classification %>% mutate(normal_and_strict_disagreements = as.numeric(llm_final_class) + llm_final_class_strict)

looking <- movies_w_llm_classification %>% select(title, normal_and_strict_disagreements, llm_final_class, llm_final_class_strict) %>% filter(llm_final_class == 0, llm_final_class_strict == 1)

movies_w_llm_classification <- movies_w_llm_classification %>%
  mutate(budget = if_else(title == "Paprika", 2600000, budget))

write.csv(movies_w_llm_classification, "data/raw/pre-2010-01-01-w-llm-classification.csv")

# movies_w_llm_classification <- read_csv("data/raw/pre-2010-01-01-w-llm-classification.csv")

movies_10k_w_llm <- movies_10k_w_llm |>
  mutate(
    llm_class_final = factor(llm_class_final,
                             levels = c(0, 1),
                             labels = c("No", "Yes"))
  )

vote_average_plot <- ggplot(movies_10k_w_llm, aes(x = vote_average, fill = llm_class_final)) +
  geom_density(position = "identity", alpha = 0.7) +
  labs(y = NULL, x = "Average User Rating", fill = "Cult Classic Status") +
  theme_classic()

log_revenue_plot <- ggplot(movies_10k_w_llm, aes(x = log(revenue), fill = llm_class_final)) +
  geom_density(position = "identity", alpha = 0.7) +
  labs(y = NULL, x = "Log Box Office Revenue", fill = "Cult Classic Status") +
  theme_classic()

log_budget_plot <- ggplot(movies_10k_w_llm, aes(x = log(budget), fill = llm_class_final)) +
  geom_density(position = "identity", alpha = 0.7) +
  labs(y = NULL, x = "Log Production Budget", fill = "Cult Classic Status") +
  theme_classic()

runtime_plot <- ggplot(movies_10k_w_llm, aes(x = runtime, fill = llm_class_final)) +
  geom_density(position = "identity", alpha = 0.7) +
  labs(y = NULL, x = "Runtime (Minutes)", fill = "Cult Classic Status") +
  theme_classic()

final_plot <- (
  (vote_average_plot | runtime_plot) /
  (log_budget_plot | log_revenue_plot)
) +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")

final_plot +
  plot_annotation(
    title = "Distribution of Movie Characteristics by LLM Cult Classification",
    caption = "TMDB and OpenAI APIs"
  )
```

```{r}
# Preliminary classification model and predictions

# Run logistic

model_logit <- glm(llm_class_final ~ vote_average + popularity + budget + revenue + adult + runtime,
                   data = movies_10k_w_llm,
                   family = binomial)
summary(model_logit)

# Predict for logistic
prediction_data <- movies_df %>% filter(budget > 10, revenue > 10, release_date >= "2010-01-01")

prediction_data$predicted_prob <- predict(model_logit, newdata = prediction_data, type = "response")

prediction_data <- prediction_data %>% arrange(desc(predicted_prob))

library(randomForest)
model_rf <- randomForest(as.factor(cult_classic) ~ budget + rating + genre + runtime,
                         data = train_data,
                         ntree = 500,
                         importance = TRUE)
```







